const ALPHA_UPPER: string = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const NUMBERS: string = "0123456789";
const TIME_SHOW_USERNAME: number = 5000;
const BASE_URL = "";
const API_URL = "ws://localhost:4000";
const SCROLL_DELAY = 1000;
const TIME_SHOW_MESSAGE = 5000;
const DELAY_RECONNECT = 3000;

export {
  ALPHA_UPPER,
  NUMBERS,
  TIME_SHOW_USERNAME,
  BASE_URL,
  API_URL,
  SCROLL_DELAY,
  TIME_SHOW_MESSAGE,
  DELAY_RECONNECT,
};
