const CARS_PER_PAGE: number = 7;
const ADDRESS: string = "http://127.0.0.1:3000";
const NUMBER_CARS_GENERATE = 100;
const FRAME_FREQUENCY = 60 / 1000;
const CAR_OFFSET = 120;

export {
  CARS_PER_PAGE,
  ADDRESS,
  NUMBER_CARS_GENERATE,
  FRAME_FREQUENCY,
  CAR_OFFSET,
};
