const ANIMATION_TIME: number = 300; // ms
const COUNT_LINES_PER_RESULT_BLOCK: number = 10;
const ALPHA_UPPER: string = "ABCDEFGHIJKLMNOPQRSTUVWXYZ-";
const KEY_USER = "user-puzzle";
const KOEF_EXT = 1.3;
const TIME_SHOW_USERNAME: number = 5000;

export {
  ANIMATION_TIME,
  ALPHA_UPPER,
  KEY_USER,
  COUNT_LINES_PER_RESULT_BLOCK,
  TIME_SHOW_USERNAME,
  KOEF_EXT,
};
